application: wwwstrategoio
runtime: python27
api_version: 1
threadsafe: true

handlers:

- script: api.app
  url: /api/.*

- login: admin
  url: /
  static_files: static/index.html
  upload: static/index.html

- login: admin
  url: /(.*)
  static_files: static/\1
  upload: static/(.*)
